use_frameworks!
pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
pod 'Alamofire', '~> 3.0'
pod 'MBProgressHUD', '~> 0.9.2'
pod "SMSwipeableTabView"
pod 'Kingfisher', '~> 2.4'
pod 'OAuthSwift', '~> 0.5.0'
pod 'SnapKit', '~> 0.15.0'
pod 'Neon'
