platform :ios, '8.0'

target 'testDiscogs' do
    # Comment this line if you're not using Swift and don't want to use dynamic frameworks

    use_frameworks!
    pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
    pod 'Alamofire', '~> 3.4'
    pod "SMSwipeableTabView"
    pod 'Kingfisher', '~> 2.4'
    #pod "Nuke" # SMSimpleListViewController
    # pod "Nuke-Alamofire-Plugin"
    # pod "Nuke-AnimatedImage-Plugin"
    pod "Preheat"
    pod 'OAuthSwift', '~> 0.5.0'
    pod 'SnapKit', '~> 0.15.0'
    pod 'RealmSwift'
    pod 'ObjectMapper', '~> 1.3'
    pod 'AlamofireObjectMapper', '~> 3.0'
    pod 'AlamofireNetworkActivityIndicator', '~> 1.0'
    pod "PKHUD"
    #pod 'Neon'
    #pod 'Cartography',  :git => 'https://github.com/robb/Cartography.git' # AlbumViewController

    
target 'testDiscogsTests' do
    
    # Pods for testing
end

target 'testDiscogsUITests' do
    
    # Pods for testing
end

end
