use_frameworks!
pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
pod 'Alamofire', '~> 3.0'
pod 'MBProgressHUD', '~> 0.9.2'
pod "SMSwipeableTabView"
pod 'Kingfisher', '~> 2.4'
pod "Nuke"
pod "Nuke-Alamofire-Plugin" # optional
pod "Nuke-AnimatedImage-Plugin" # optional
pod "Preheat"
pod 'OAuthSwift', '~> 0.5.0'
pod 'SnapKit', '~> 0.15.0'
#pod 'Neon'
pod 'Cartography',  :git => 'https://github.com/robb/Cartography.git'